//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMembership.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int AnsGroupID { get; set; }
        public int SXQID { get; set; }
        public string AnsText { get; set; }
        public System.DateTime DateEntered { get; set; }
        public Nullable<System.Guid> CreatedByUser { get; set; }
    
        public virtual SurveyXQuestion SurveyXQuestion { get; set; }
    }
}
