//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SampleMembership.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Survey()
        {
            this.SurveyXQuestions = new HashSet<SurveyXQuestion>();
        }
    
        public int SurveyID { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyXQuestion> SurveyXQuestions { get; set; }

        [Display(Name = "Questions")]
        public List<Question> SurveyQuestions = new List<Question>();

        [Display(Name = "SXQIDs")]
        public List<SurveyXQuestion> SXQIDs = new List<SurveyXQuestion>();
    }
}
