//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMembership.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Survey()
        {
            this.SurveyXQuestions = new HashSet<SurveyXQuestion>();
        }
    
        public int? QuestionID { get; set; }

        public int SurveyID { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyXQuestion> SurveyXQuestions { get; set; }
		[Display(Name = "Questions")]
		public List<Question> SurveyQuestions = new List<Question>();

        [Display(Name = "NonQuestions")]
        public List<Question> AllQuestions = new List<Question>();

        [Display(Name = "SXQIDs")]
		public List<int> SXQIDs = new List<int>();

        public IEnumerable<SelectListItem> Questions { get; set; }
    }
}
